version: '2.0'
services:
  mysql:
    restart: always
    image: mysql:5.5
    container_name: app-mysql
    ports:
      - "8001:3306"
    volumes:
      - ./docker_build/mysql/conf:/etc/mysql/conf.d
      - ./docker_build/mysql/data:/var/lib/mysql
#      - ./docker_build/mysql/init.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: app

  redis:
    restart: always
    image: redis:latest
    container_name: app-redis
    ports:
      - "8002:6379"
    volumes:
      - ./docker_build/redis/data:/data
    command: redis-server --requirepass password --appendonly yes

  web:
    restart: always
    build: "."
    container_name: app
    expose:
      - "3000"
#    volumes:
#      - ./:/opt/app
    environment:
      DEBUG: 'false'
      PORT: 3000
      REDIS_URI: localhost:6379
      REDIS_PASSOWRD: password
      # change 192.168.0.106 to your internal ip
      CONNECTION_STRING: root:123456@tcp(mysql:3306)/app?charset=utf8mb4&parseTime=True&loc=Local
    ports:
      - "3000:3000"
    links:
      - mysql
      - redis
    depends_on:
       - mysql
       - redis
